<?php
/**
 * nl.sp.drupal-event-registration
 * Functionaliteit om snel ter plekke deelnemers te registreren bij een evenement
 */

/**
 * Implements hook_menu().
 */
function speventreg_menu() {

  $items = [];
  $items['evenementregistratie'] = [
    'title'           => 'Evenementregistratie',
    'type'            => MENU_NORMAL_ITEM,
    'page callback'   => 'speventreg_page_overview',
    'access callback' => 'speventreg_check_access',
    'file'            => 'speventreg.page-overview.inc',
  ];
  $items['evenementregistratie/participants'] = [
    'title'           => 'Deelnemers aanmelden',
    'type'            => MENU_CALLBACK,
    'page callback'   => 'speventreg_page_participants',
    'access callback' => 'speventreg_check_access',
    'file'            => 'speventreg.page-participants.inc',
  ];
  $items['evenementregistratie/status/%/%'] = [
    'title'           => 'Deelnemerstatus wijzigen',
    'type'            => MENU_CALLBACK,
    'page callback'   => 'speventreg_page_partstatus',
    'page arguments'   => [2, 3],
    'access callback' => 'speventreg_check_access',
    'file'            => 'speventreg.page-participants.inc',
  ];
  $items['evenementregistratie/autocomplete'] = [
    'title'           => 'Autocomplete deelnemers/leden',
    'type'            => MENU_CALLBACK,
    'page callback'   => 'speventreg_page_autocomplete',
    'access callback' => 'speventreg_check_access',
    'file'            => 'speventreg.page-participants.inc',
  ];

  return $items;
}

/**
 * Implements hook_theme().
 */
function speventreg_theme($existing, $type, $theme, $path) {
  return [
    'speventreg-tpl-participants' => [
      'template'  => 'speventreg-tpl-participants',
      'variables' => ['events' => [], 'participants' => []],
    ],
  ];
}

/**
 * Access check of een gebruiker toegang heeft tot deze module en het overzicht van evenementen.
 * Voor nu houden we het lekker simpel... alleen toegang voor Drupal- of CiviCRM-admins.
 * @return bool Has access
 */
function speventreg_check_access() {

  global $user;
  $access = user_access('administer CiviCRM') || in_array('administrator', $user->roles);

  return $access;
}
