<?php
/**
 * nl.sp.drupal-event-registration
 * Functionaliteit om snel ter plekke deelnemers te registreren bij een evenement
 */

/**
 * Implements hook_menu().
 */
function speventreg_menu() {

  $items = [];
  $items['evenementregistratie'] = [
    'title'           => 'Evenementregistratie',
    'type'            => MENU_NORMAL_ITEM,
    'page callback'   => 'speventreg_page_overview',
    'access callback' => 'speventreg_check_access',
    'file'            => 'speventreg.page-overview.inc',
  ];
  $items['evenementregistratie/participants'] = [
    'title'           => 'Deelnemers aanmelden',
    'type'            => MENU_CALLBACK,
    'page callback'   => 'speventreg_page_participants',
    'access callback' => 'speventreg_check_access',
    'file'            => 'speventreg.page-participants.inc',
  ];
  $items['evenementregistratie/status/%/%'] = [
    'title'           => 'Deelnemerstatus wijzigen',
    'type'            => MENU_CALLBACK,
    'page callback'   => 'speventreg_page_partstatus',
    'access callback' => 'speventreg_check_access',
    'file'            => 'speventreg.page-partupdate.inc',
  ];
  $items['evenementregistratie/add/%/%'] = [
    'title'           => 'Deelnemer toevoegen',
    'type'            => MENU_CALLBACK,
    'page callback'   => 'speventreg_page_partadd',
    'access callback' => 'speventreg_check_access',
    'file'            => 'speventreg.page-partupdate.inc',
  ];
  $items['evenementregistratie/edit/%/%/%'] = [
    'title'           => 'Deelnemer vervangen',
    'type'            => MENU_CALLBACK,
    'page callback'   => 'speventreg_page_partedit',
    'access callback' => 'speventreg_check_access',
    'file'            => 'speventreg.page-partupdate.inc',
  ];
  $items['evenementregistratie/autocomplete'] = [
    'title'           => 'Autocomplete deelnemers/leden',
    'type'            => MENU_CALLBACK,
    'page callback'   => 'speventreg_page_autocomplete',
    'access callback' => 'speventreg_check_access',
    'file'            => 'speventreg.page-partupdate.inc',
  ];

  return $items;
}

/**
 * Access check of een gebruiker toegang heeft tot deze module en het overzicht van evenementen.
 * Voor nu houden we het lekker simpel... alleen toegang voor admins.
 * @return bool Has access
 */
function speventreg_check_access() {
  global $user;
  $access = user_access('administer CiviCRM') || in_array('administrator', $user->roles);

  return $access;
}
